name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install required software
      run: sudo apt-get install git build-essential -y

    - name: Install dependencies
      run: make

    - name: Compile everything
      run: make everything

